export const USER_LOGIN_REQUEST = 'AUTHENTICATION.USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'AUTHENTICATION.USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'AUTHENTICATION.USER_LOGIN_FAILURE';

export const USER_LOGOUT_SUCCESS = 'AUTHENTICATION.USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_REQUEST = 'AUTHENTICATION.USER_LOGOUT_REQUEST';
export const USER_LOGOUT_FAILURE = 'AUTHENTICATION.USER_LOGOUT_FAILURE';

export const USER_REGISTER_SUCCESS = 'AUTHENTICATION.USER_REGISTER_SUCCESS';
export const USER_REGISTER_REQUEST = 'AUTHENTICATION.USER_REGISTER_REQUEST';
export const USER_REGISTER_FAILURE = 'AUTHENTICATION.USER_REGISTER_FAILURE';

export const USER_AVATAR_SUCCESS = 'AUTHENTICATION.USER_AVATAR_SUCCESS';
export const USER_AVATAR_REQUEST = 'AUTHENTICATION.USER_AVATAR_REQUEST';
export const USER_AVATAR_FAILURE = 'AUTHENTICATION.USER_AVATAR_FAILURE';

export const USER_LOGIN_STORAGE_FAILURE =
  'AUTHENTICATION.USER_LOGIN_STORAGE_FAILURE';
export const USER_LOGIN_STORAGE_REQUEST =
  'AUTHENTICATION.USER_LOGIN_STORAGE_REQUEST';
export const USER_LOGIN_STORAGE_SUCCESS =
  'AUTHENTICATION.USER_LOGIN_STORAGE_SUCCESS';
