export const CREATE_POST_REQUEST = 'FEED.CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'FEED.CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'FEED.CREATE_POST_FAILURE';

export const SINGLE_USER_POSTS_REQUEST = 'SINGLE_USER_POSTS_REQUEST';
export const SINGLE_USER_POSTS_SUCCESS = 'SINGLE_USER_POSTS_SUCCESS';
export const SINGLE_USER_POSTS_FAILURE = 'SINGLE_USER_POSTS_FAILURE';
