// POST TYPES

export const CREATE_POST_REQUEST = 'FEED.CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'FEED.CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'FEED.CREATE_POST_FAILURE';

export const USERS_POSTS_REQUEST = 'FEED.USERS_POSTS_REQUEST';
export const USERS_POSTS_SUCCESS = 'FEED.USERS_POSTS_SUCCESS';
export const USERS_POSTS_FAILURE = 'FEED.USERS_POSTS_FAILURE';

export const FOLLOWING_USERS_POSTS_REQUEST =
  'FEED.FOLLOWING_USERS_POSTS_REQUEST';
export const FOLLOWING_USERS_POSTS_SUCCESS =
  'FEED.FOLLOWING_USERS_POSTS_SUCCESS';
export const FOLLOWING_USERS_POSTS_FAILURE =
  'FEED.FOLLOWING_USERS_POSTS_FAILURE';

export const SAVED_POSTS_REQUEST = 'FEED.SAVED_POSTS_REQUEST';
export const SAVED_POSTS_SUCCESS = 'FEED.SAVED_POSTS_SUCCESS';
export const SAVED_POSTS_FAILURE = 'FEED.SAVED_POSTS_FAILURE';

export const SINGLE_USER_POSTS_REQUEST = 'FEED.SINGLE_USER_POSTS_REQUEST';
export const SINGLE_USER_POSTS_SUCCESS = 'FEED.SINGLE_USER_POSTS_SUCCESS';
export const SINGLE_USER_POSTS_FAILURE = 'FEED.SINGLE_USER_POSTS_FAILURE';

export const SINGLE_POST_REQUEST = 'FEED.SINGLE_POST_REQUEST';
export const SINGLE_POST_SUCCESS = 'FEED.SINGLE_POST_SUCCESS';
export const SINGLE_POST_FAILURE = 'FEED.SINGLE_POST_FAILURE';

export const DELETE_POST_REQUEST = 'FEED.DELETE_POST.REQUEST';
export const DELETE_POST_SUCCESS = 'FEED.DELETE_POST.SUCCESS';
export const DELETE_POST_FAILURE = 'FEED.DELETE_POST.FAILURE';

export const TOGGLE_SAVE_POST_REQUEST = 'FEED.TOGGLE_SAVE_POST_REQUEST';
export const TOGGLE_SAVE_POST_SUCCESS = 'FEED.TOGGLE_SAVE_POST_SUCCESS';
export const TOGGLE_SAVE_POST_FAILURE = 'FEED.TOGGLE_SAVE_POST_FAILURE';

export const TOGGLE_LIKE_POST_REQUEST = 'FEED.TOGGLE_LIKE_POST_REQUEST';
export const TOGGLE_LIKE_POST_SUCCESS = 'FEED.TOGGLE_LIKE_POST_SUCCESS';
export const TOGGLE_LIKE_POST_FAILURE = 'FEED.TOGGLE_LIKE_POST_FAILURE';

// COMMENT TYPES

export const CREATE_COMMENT_REQUEST = 'FEED.CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'FEED.CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'FEED.CREATE_COMMENT_FAILURE';

export const DELETE_COMMENT_REQUEST = 'FEED.DELETE_COMMENT.REQUEST';
export const DELETE_COMMENT_SUCCESS = 'FEED.DELETE_COMMENT.SUCCESS';
export const DELETE_COMMENT_FAILURE = 'FEED.DELETE_COMMENT.FAILURE';

export const TOGGLE_LIKE_COMMENT_REQUEST = 'FEED.TOGGLE_LIKE_COMMENT_REQUEST';
export const TOGGLE_LIKE_COMMENT_SUCCESS = 'FEED.TOGGLE_LIKE_COMMENT_SUCCESS';
export const TOGGLE_LIKE_COMMENT_FAILURE = 'FEED.TOGGLE_LIKE_COMMENT_FAILURE';
