export const SINGLE_USER_REQUEST = 'USERS.SINGLE_USER_REQUEST';
export const SINGLE_USER_SUCCESS = 'USERS.SINGLE_USER_SUCCESS';
export const SINGLE_USER_FAILURE = 'USERS.SINGLE_USER_FAILURE';

export const TOGGLE_FOLLOW_USER_REQUEST = 'USERS.TOGGLE_FOLLOW_USER_REQUEST';
export const TOGGLE_FOLLOW_USER_SUCCESS = 'USERS.TOGGLE_FOLLOW_USER_SUCCESS';
export const TOGGLE_FOLLOW_USER_FAILURE = 'USERS.TOGGLE_FOLLOW_USER_FAILURE';

export const FOLLOWERS_REQUEST = 'USERS.FOLLOWERS_REQUEST';
export const FOLLOWERS_SUCCESS = 'USERS.FOLLOWERS_SUCCESS';
export const FOLLOWERS_FAILURE = 'USERS.FOLLOWERS_FAILURE';

export const FOLLOWING_USERS_REQUEST = 'USERS.FOLLOWING_USERS_REQUEST';
export const FOLLOWING_USERS_SUCCESS = 'USERS.FOLLOWING_USERS_SUCCESS';
export const FOLLOWING_USERS_FAILURE = 'USERS.FOLLOWING_USERS_FAILURE';

export const NOT_FOLLOWED_USERS_REQUEST = 'USERS.NOT_FOLLOWED_USERS_REQUEST';
export const NOT_FOLLOWED_USERS_SUCCESS = 'USERS.NOT_FOLLOWED_USERS_SUCCESS';
export const NOT_FOLLOWED_USERS_FAILURE = 'USERS.NOT_FOLLOWED_USERS_FAILURE';

export const SEARCH_USER_REQUEST = 'USERS.SEARCH_USER_REQUEST';
export const SEARCH_USER_SUCCESS = 'USERS.SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAILURE = 'USERS.SEARCH_USER_FAILURE';

export const INC_PROFILE_USER_POST_COUNT = 'USERS.INC_PROFILE_USER_POST_COUNT';
export const DEC_PROFILE_USER_POST_COUNT = 'USERS.DEC_PROFILE_USER_POST_COUNT';
